site_name: Sentyment

nav:
        - Introduction: index.md

        - Cordinator:
                - General overview: 'cordinator/cordinator-description.md'
                - Main component: 'cordinator/cordinator-component.md'
        - Data Module:
                - General overview: 'data-module/data-description.md'
                - Main component: 'data-module/data-component.md'
        - Ai Module:
                - General overview: 'ai-module/ai-description.md'
                - Main component: 'ai-module/ai-component.md'
        - Trading Module:
                - General overview: 'trading-module/trading-description.md'
                - Main component: 'trading-module/trading-component.md'

theme:
        name: readthedocs        
